Repository malivinayak/To-Do-Manager, pull requests merged in 2023-10, with the labels that each got.

#28 style: Title and input placeholder
  assets/main.css
  index.html
Labels: hacktoberfest-accepted

#30 style: Title and input placeholder
  assets/main.css
  index.html
Labels: hacktoberfest-accepted

#34 fix: bug fix of adding same task again
  assets/to-do-task/loadTask.js
  assets/to-do-task/storeTask.js
  index.html
Labels: bug, hacktoberfest-accepted

#41 feat: alert box on successful deletion of tasks
  assets/custom-alert/alert.css
  assets/custom-alert/alerttaskadded.css
  assets/to-do-task/storeTask.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#48 refactor: alert closing, edit alert, confirmation for deletion
  assets/custom-alert/alert.css
  assets/custom-alert/alert.js
  assets/to-do-task/storeTask.js
  index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#51 Updated the Readme.
  README.md
  assets/Images/TodoManager.png
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#50 refactor: added favicon and og property
  assets/images/to-do icon.png
  index.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#55 feat: add Contributors name automatically to README
  .github/workflows/Contributors.yml
  README.md
Labels: documentation
